# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anamenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1398, 791)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1381, 751))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QGroupBox {\n"
"    background-color: #FFEBEE;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(-410, -40, 1791, 761))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #FFEBEE;\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(620, 300, 55, 16))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(430, 560, 451, 123))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lblAcilIletisimBilgi = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblAcilIletisimBilgi.setFont(font)
        self.lblAcilIletisimBilgi.setObjectName("lblAcilIletisimBilgi")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblAcilIletisimBilgi)
        self.lblYakinAdi = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblYakinAdi.setFont(font)
        self.lblYakinAdi.setObjectName("lblYakinAdi")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblYakinAdi)
        self.lneYakinAdi = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lneYakinAdi.setInputMask("")
        self.lneYakinAdi.setObjectName("lneYakinAdi")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneYakinAdi)
        self.lblYakinSoyadi = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblYakinSoyadi.setFont(font)
        self.lblYakinSoyadi.setObjectName("lblYakinSoyadi")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblYakinSoyadi)
        self.lneYakinSoyadi = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lneYakinSoyadi.setInputMask("")
        self.lneYakinSoyadi.setObjectName("lneYakinSoyadi")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneYakinSoyadi)
        self.lblYakinTelefon = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblYakinTelefon.setFont(font)
        self.lblYakinTelefon.setObjectName("lblYakinTelefon")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblYakinTelefon)
        self.lneYakinTelefon = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lneYakinTelefon.setObjectName("lneYakinTelefon")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lneYakinTelefon)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(430, 70, 451, 221))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lblBagisciBilgi = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblBagisciBilgi.setFont(font)
        self.lblBagisciBilgi.setObjectName("lblBagisciBilgi")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblBagisciBilgi)
        self.lblBagisciAdi = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBagisciAdi.setFont(font)
        self.lblBagisciAdi.setObjectName("lblBagisciAdi")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblBagisciAdi)
        self.lneBagisciAdi = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lneBagisciAdi.setInputMask("")
        self.lneBagisciAdi.setText("")
        self.lneBagisciAdi.setPlaceholderText("")
        self.lneBagisciAdi.setObjectName("lneBagisciAdi")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneBagisciAdi)
        self.lblBagisciSoyadi = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBagisciSoyadi.setFont(font)
        self.lblBagisciSoyadi.setObjectName("lblBagisciSoyadi")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblBagisciSoyadi)
        self.lneBagisciSoyadi = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lneBagisciSoyadi.setInputMask("")
        self.lneBagisciSoyadi.setPlaceholderText("")
        self.lneBagisciSoyadi.setObjectName("lneBagisciSoyadi")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneBagisciSoyadi)
        self.lblTc = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTc.setFont(font)
        self.lblTc.setObjectName("lblTc")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblTc)
        self.lneTc = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lneTc.setObjectName("lneTc")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lneTc)
        self.lblCinsiyet = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblCinsiyet.setFont(font)
        self.lblCinsiyet.setObjectName("lblCinsiyet")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblCinsiyet)
        self.cmbCinsiyet = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.cmbCinsiyet.setCurrentText("")
        self.cmbCinsiyet.setObjectName("cmbCinsiyet")
        self.cmbCinsiyet.addItem("")
        self.cmbCinsiyet.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbCinsiyet)
        self.dteDogumTarihi = QtWidgets.QDateEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dteDogumTarihi.setFont(font)
        self.dteDogumTarihi.setCalendarPopup(True)
        self.dteDogumTarihi.setObjectName("dteDogumTarihi")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dteDogumTarihi)
        self.lblDogumTarihi = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDogumTarihi.setFont(font)
        self.lblDogumTarihi.setObjectName("lblDogumTarihi")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblDogumTarihi)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(430, 360, 451, 133))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblIletisimBilgi = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblIletisimBilgi.setFont(font)
        self.lblIletisimBilgi.setObjectName("lblIletisimBilgi")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblIletisimBilgi)
        self.lblBagisciTelefon = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBagisciTelefon.setFont(font)
        self.lblBagisciTelefon.setObjectName("lblBagisciTelefon")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblBagisciTelefon)
        self.lneBagisciTelefon = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lneBagisciTelefon.setPlaceholderText("")
        self.lneBagisciTelefon.setObjectName("lneBagisciTelefon")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneBagisciTelefon)
        self.lblBagisciEposta = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBagisciEposta.setFont(font)
        self.lblBagisciEposta.setObjectName("lblBagisciEposta")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblBagisciEposta)
        self.lneBagisciEposta = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lneBagisciEposta.setObjectName("lneBagisciEposta")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneBagisciEposta)
        self.lblBagisciEv = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBagisciEv.setFont(font)
        self.lblBagisciEv.setObjectName("lblBagisciEv")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblBagisciEv)
        self.lneBagisciEv = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lneBagisciEv.setObjectName("lneBagisciEv")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lneBagisciEv)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(560, 140, 1391, 1001))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Resimler/Ekran Görüntüleri/kan5.png"))
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label_18.raise_()
        self.formLayoutWidget_5.raise_()
        self.formLayoutWidget_3.raise_()
        self.formLayoutWidget_4.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(-80, -50, 1461, 771))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: #FFEBEE;\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(620, 300, 55, 16))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(100, 500, 531, 155))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.txeNotBilgisi = QtWidgets.QTextEdit(self.formLayoutWidget_6)
        self.txeNotBilgisi.setObjectName("txeNotBilgisi")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.txeNotBilgisi)
        self.lblOnemliBilgi = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblOnemliBilgi.setFont(font)
        self.lblOnemliBilgi.setObjectName("lblOnemliBilgi")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblOnemliBilgi)
        self.lblNotBilgisi = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNotBilgisi.setFont(font)
        self.lblNotBilgisi.setObjectName("lblNotBilgisi")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lblNotBilgisi)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(100, 80, 531, 331))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblTibbiBilgiler = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTibbiBilgiler.setFont(font)
        self.lblTibbiBilgiler.setObjectName("lblTibbiBilgiler")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblTibbiBilgiler)
        self.lblKilo = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblKilo.setFont(font)
        self.lblKilo.setObjectName("lblKilo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblKilo)
        self.spnKilo = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spnKilo.setMinimum(45)
        self.spnKilo.setMaximum(150)
        self.spnKilo.setSingleStep(1)
        self.spnKilo.setProperty("value", 45)
        self.spnKilo.setObjectName("spnKilo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnKilo)
        self.lblBoy = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBoy.setFont(font)
        self.lblBoy.setObjectName("lblBoy")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblBoy)
        self.lneBoy = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lneBoy.setObjectName("lneBoy")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneBoy)
        self.lblKronikHastalik = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblKronikHastalik.setFont(font)
        self.lblKronikHastalik.setObjectName("lblKronikHastalik")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblKronikHastalik)
        self.chkbKronikHastalik = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chkbKronikHastalik.setObjectName("chkbKronikHastalik")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chkbKronikHastalik)
        self.lblIlac = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblIlac.setFont(font)
        self.lblIlac.setObjectName("lblIlac")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblIlac)
        self.chkbIlac = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chkbIlac.setObjectName("chkbIlac")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chkbIlac)
        self.lblAlerji = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAlerji.setFont(font)
        self.lblAlerji.setObjectName("lblAlerji")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblAlerji)
        self.chkbAlerji = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chkbAlerji.setObjectName("chkbAlerji")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.chkbAlerji)
        self.lblSigara = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSigara.setFont(font)
        self.lblSigara.setObjectName("lblSigara")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblSigara)
        self.chkbSigara = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.chkbSigara.setObjectName("chkbSigara")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.chkbSigara)
        self.lblGecmisMudahale = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGecmisMudahale.setFont(font)
        self.lblGecmisMudahale.setObjectName("lblGecmisMudahale")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblGecmisMudahale)
        self.txeGecmisMudahale = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.txeGecmisMudahale.setObjectName("txeGecmisMudahale")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txeGecmisMudahale)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(-470, 50, 1951, 781))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Resimler/Ekran Görüntüleri/kan14.png"))
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label_19.raise_()
        self.formLayoutWidget_6.raise_()
        self.formLayoutWidget_2.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setGeometry(QtCore.QRect(-10, 0, 1391, 721))
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    background-color: #FFEBEE;\n"
"}\n"
"")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(620, 300, 55, 16))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 491, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblBagisBilgi = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblBagisBilgi.setFont(font)
        self.lblBagisBilgi.setObjectName("lblBagisBilgi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblBagisBilgi)
        self.lblKanGrubu = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblKanGrubu.setFont(font)
        self.lblKanGrubu.setObjectName("lblKanGrubu")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblKanGrubu)
        self.cmbKanGrubu = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmbKanGrubu.setObjectName("cmbKanGrubu")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbKanGrubu)
        self.lblRhFaktoru = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRhFaktoru.setFont(font)
        self.lblRhFaktoru.setObjectName("lblRhFaktoru")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblRhFaktoru)
        self.cmbRhFaktoru = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmbRhFaktoru.setObjectName("cmbRhFaktoru")
        self.cmbRhFaktoru.addItem("")
        self.cmbRhFaktoru.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbRhFaktoru)
        self.lblBagisTuru = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBagisTuru.setFont(font)
        self.lblBagisTuru.setObjectName("lblBagisTuru")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblBagisTuru)
        self.cmbBagisTuru = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmbBagisTuru.setObjectName("cmbBagisTuru")
        self.cmbBagisTuru.addItem("")
        self.cmbBagisTuru.addItem("")
        self.cmbBagisTuru.addItem("")
        self.cmbBagisTuru.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbBagisTuru)
        self.lblSehir = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSehir.setFont(font)
        self.lblSehir.setObjectName("lblSehir")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblSehir)
        self.cmbSehir = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmbSehir.setObjectName("cmbSehir")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.cmbSehir.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbSehir)
        self.lblIlkKanBagisi = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblIlkKanBagisi.setFont(font)
        self.lblIlkKanBagisi.setObjectName("lblIlkKanBagisi")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lblIlkKanBagisi)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label)
        self.lneSonKanBagisiTarihi = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneSonKanBagisiTarihi.setPlaceholderText("")
        self.lneSonKanBagisiTarihi.setObjectName("lneSonKanBagisiTarihi")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lneSonKanBagisiTarihi)
        self.lblSonKanBagisiTarihi = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSonKanBagisiTarihi.setFont(font)
        self.lblSonKanBagisiTarihi.setObjectName("lblSonKanBagisiTarihi")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblSonKanBagisiTarihi)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.chkblkKanBagisi = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chkblkKanBagisi.setObjectName("chkblkKanBagisi")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.chkblkKanBagisi)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1070, 320, 291, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.psbRandevuAl = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.psbRandevuAl.setFont(font)
        self.psbRandevuAl.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 red, stop:1 white); /* Arka plan geçişi */\n"
"    border: 2px solid transparent;  /* Şeffaf kenar */\n"
"    border-radius: 15px;  /* Oval köşeler */\n"
"    padding: 5px;  /* İç kenar boşluğu */\n"
"    border-image: linear-gradient(to right, red, white) 1;  /* Kenar geçişi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 white, stop:1 red); /* Tıklanınca arka plan geçişi tersine dönüyor */\n"
"    border: 2px solid red; /* Tıklanınca kenarlık kırmızı oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psbRandevuAl.setObjectName("psbRandevuAl")
        self.verticalLayout_2.addWidget(self.psbRandevuAl)
        self.psRandevuAra = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.psRandevuAra.setFont(font)
        self.psRandevuAra.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 red, stop:1 white); /* Arka plan geçişi */\n"
"    border: 2px solid transparent;  /* Şeffaf kenar */\n"
"    border-radius: 15px;  /* Oval köşeler */\n"
"    padding: 5px;  /* İç kenar boşluğu */\n"
"    border-image: linear-gradient(to right, red, white) 1;  /* Kenar geçişi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 white, stop:1 red); /* Tıklanınca arka plan geçişi tersine dönüyor */\n"
"    border: 2px solid red; /* Tıklanınca kenarlık kırmızı oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psRandevuAra.setObjectName("psRandevuAra")
        self.verticalLayout_2.addWidget(self.psRandevuAra)
        self.psGuncelle = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.psGuncelle.setFont(font)
        self.psGuncelle.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 red, stop:1 white); /* Arka plan geçişi */\n"
"    border: 2px solid transparent;  /* Şeffaf kenar */\n"
"    border-radius: 15px;  /* Oval köşeler */\n"
"    padding: 5px;  /* İç kenar boşluğu */\n"
"    border-image: linear-gradient(to right, red, white) 1;  /* Kenar geçişi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 white, stop:1 red); /* Tıklanınca arka plan geçişi tersine dönüyor */\n"
"    border: 2px solid red; /* Tıklanınca kenarlık kırmızı oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psGuncelle.setObjectName("psGuncelle")
        self.verticalLayout_2.addWidget(self.psGuncelle)
        self.psRandevuListele = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.psRandevuListele.setFont(font)
        self.psRandevuListele.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 red, stop:1 white); /* Arka plan geçişi */\n"
"    border: 2px solid transparent;  /* Şeffaf kenar */\n"
"    border-radius: 15px;  /* Oval köşeler */\n"
"    padding: 5px;  /* İç kenar boşluğu */\n"
"    border-image: linear-gradient(to right, red, white) 1;  /* Kenar geçişi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 white, stop:1 red); /* Tıklanınca arka plan geçişi tersine dönüyor */\n"
"    border: 2px solid red; /* Tıklanınca kenarlık kırmızı oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psRandevuListele.setObjectName("psRandevuListele")
        self.verticalLayout_2.addWidget(self.psRandevuListele)
        self.psCikis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.psCikis.setFont(font)
        self.psCikis.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 red, stop:1 white); /* Arka plan geçişi */\n"
"    border: 2px solid transparent;  /* Şeffaf kenar */\n"
"    border-radius: 15px;  /* Oval köşeler */\n"
"    padding: 5px;  /* İç kenar boşluğu */\n"
"    border-image: linear-gradient(to right, red, white) 1;  /* Kenar geçişi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 white, stop:1 red); /* Tıklanınca arka plan geçişi tersine dönüyor */\n"
"    border: 2px solid red; /* Tıklanınca kenarlık kırmızı oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psCikis.setObjectName("psCikis")
        self.verticalLayout_2.addWidget(self.psCikis)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(870, 20, 491, 281))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.lblKanRandevuTarihi = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblKanRandevuTarihi.setFont(font)
        self.lblKanRandevuTarihi.setObjectName("lblKanRandevuTarihi")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lblKanRandevuTarihi)
        self.line_7 = QtWidgets.QFrame(self.formLayoutWidget_7)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.line_7)
        self.cldwKanBagisTarihi = QtWidgets.QCalendarWidget(self.formLayoutWidget_7)
        self.cldwKanBagisTarihi.setObjectName("cldwKanBagisTarihi")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cldwKanBagisTarihi)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(-1170, 310, 2191, 771))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../Resimler/Ekran Görüntüleri/kan11.png"))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tblwKayitTutucu = QtWidgets.QTableWidget(self.tab_4)
        self.tblwKayitTutucu.setGeometry(QtCore.QRect(0, 20, 1371, 561))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tblwKayitTutucu.setFont(font)
        self.tblwKayitTutucu.setStyleSheet("\n"
"QHeaderView::section {\n"
"    background-color: lightgray;\n"
"    padding: 4px;\n"
"    font-size: 7pt;\n"
"}\n"
"QTableWidget {\n"
"    gridline-color: black;\n"
"    font-size: 7pt;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\"\"\")\n"
"")
        self.tblwKayitTutucu.setRowCount(100)
        self.tblwKayitTutucu.setColumnCount(27)
        self.tblwKayitTutucu.setObjectName("tblwKayitTutucu")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setGeometry(QtCore.QRect(-50, -40, 1431, 761))
        self.groupBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setStyleSheet("QGroupBox {\n"
"    background-color: #FFEBEE;\n"
"}\n"
"")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(620, 300, 55, 16))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.psRavdevuSil = QtWidgets.QPushButton(self.groupBox_6)
        self.psRavdevuSil.setGeometry(QtCore.QRect(1128, 630, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.psRavdevuSil.setFont(font)
        self.psRavdevuSil.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 red, stop:1 white); /* Arka plan geçişi */\n"
"    border: 2px solid transparent;  /* Şeffaf kenar */\n"
"    border-radius: 15px;  /* Oval köşeler */\n"
"    padding: 5px;  /* İç kenar boşluğu */\n"
"    border-image: linear-gradient(to right, red, white) 1;  /* Kenar geçişi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 white, stop:1 red); /* Tıklanınca arka plan geçişi tersine dönüyor */\n"
"    border: 2px solid red; /* Tıklanınca kenarlık kırmızı oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psRavdevuSil.setObjectName("psRavdevuSil")
        self.groupBox_6.raise_()
        self.tblwKayitTutucu.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QtCore.QRect(-70, 0, 1451, 721))
        self.groupBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setStyleSheet("QGroupBox {\n"
"    background-color: #FFEBEE;\n"
"}\n"
"")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(620, 300, 55, 16))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setGeometry(QtCore.QRect(90, 40, 1131, 591))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #FFCCCC;  /* Arka plan rengini açık kırmızı yapar */\n"
"    border: 1px solid gray;  /* İsteğe bağlı olarak kenarlık ekleyebilirsiniz */\n"
"    border-radius: 5px;  /* Köşeleri yuvarlatmak için */\n"
"    margin-top: 20px;  /* Grup başlığının üstüne boşluk bırakmak için */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;  /* Başlık pozisyonunu ortalayın */\n"
"    padding: 0 3px;\n"
"    background-color: #FFCCCC;  /* Başlığın arka plan rengini aynı yapın */\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblNedenKanBagisi = QtWidgets.QLabel(self.groupBox_2)
        self.lblNedenKanBagisi.setGeometry(QtCore.QRect(10, 70, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lblNedenKanBagisi.setFont(font)
        self.lblNedenKanBagisi.setObjectName("lblNedenKanBagisi")
        self.txeNedenKanBagisi = QtWidgets.QTextEdit(self.groupBox_2)
        self.txeNedenKanBagisi.setEnabled(False)
        self.txeNedenKanBagisi.setGeometry(QtCore.QRect(10, 100, 241, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txeNedenKanBagisi.setFont(font)
        self.txeNedenKanBagisi.setReadOnly(True)
        self.txeNedenKanBagisi.setObjectName("txeNedenKanBagisi")
        self.lblAferez = QtWidgets.QLabel(self.groupBox_2)
        self.lblAferez.setGeometry(QtCore.QRect(330, 70, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lblAferez.setFont(font)
        self.lblAferez.setObjectName("lblAferez")
        self.txeAferez = QtWidgets.QTextEdit(self.groupBox_2)
        self.txeAferez.setEnabled(False)
        self.txeAferez.setGeometry(QtCore.QRect(330, 100, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txeAferez.setFont(font)
        self.txeAferez.setReadOnly(True)
        self.txeAferez.setObjectName("txeAferez")
        self.lblImmun = QtWidgets.QLabel(self.groupBox_2)
        self.lblImmun.setGeometry(QtCore.QRect(10, 290, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.lblImmun.setFont(font)
        self.lblImmun.setObjectName("lblImmun")
        self.txeImmun = QtWidgets.QTextEdit(self.groupBox_2)
        self.txeImmun.setEnabled(False)
        self.txeImmun.setGeometry(QtCore.QRect(10, 320, 241, 131))
        self.txeImmun.setReadOnly(True)
        self.txeImmun.setObjectName("txeImmun")
        self.lblKokHucre = QtWidgets.QLabel(self.groupBox_2)
        self.lblKokHucre.setGeometry(QtCore.QRect(330, 290, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.lblKokHucre.setFont(font)
        self.lblKokHucre.setObjectName("lblKokHucre")
        self.txeKokHucre = QtWidgets.QTextEdit(self.groupBox_2)
        self.txeKokHucre.setEnabled(False)
        self.txeKokHucre.setGeometry(QtCore.QRect(330, 320, 251, 131))
        self.txeKokHucre.setReadOnly(True)
        self.txeKokHucre.setObjectName("txeKokHucre")
        self.lblHerBagis = QtWidgets.QLabel(self.groupBox_2)
        self.lblHerBagis.setGeometry(QtCore.QRect(780, 510, 361, 151))
        self.lblHerBagis.setText("")
        self.lblHerBagis.setPixmap(QtGui.QPixmap("../../Resimler/Ekran Görüntüleri/resim16.png"))
        self.lblHerBagis.setObjectName("lblHerBagis")
        self.lblAferez_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lblAferez_2.setGeometry(QtCore.QRect(640, 70, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lblAferez_2.setFont(font)
        self.lblAferez_2.setObjectName("lblAferez_2")
        self.txeAferez_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.txeAferez_2.setEnabled(False)
        self.txeAferez_2.setGeometry(QtCore.QRect(640, 100, 421, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txeAferez_2.setFont(font)
        self.txeAferez_2.setReadOnly(True)
        self.txeAferez_2.setObjectName("txeAferez_2")
        self.lblKokHucre_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lblKokHucre_2.setGeometry(QtCore.QRect(650, 290, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lblKokHucre_2.setFont(font)
        self.lblKokHucre_2.setObjectName("lblKokHucre_2")
        self.txeKokHucre_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.txeKokHucre_2.setEnabled(False)
        self.txeKokHucre_2.setGeometry(QtCore.QRect(650, 320, 411, 131))
        self.txeKokHucre_2.setReadOnly(True)
        self.txeKokHucre_2.setObjectName("txeKokHucre_2")
        self.txeBilgiKutusu = QtWidgets.QTextEdit(self.groupBox_7)
        self.txeBilgiKutusu.setEnabled(True)
        self.txeBilgiKutusu.setGeometry(QtCore.QRect(90, 20, 191, 41))
        self.txeBilgiKutusu.setStyleSheet("\n"
"    background-color: #FFCCCC;  /* Arka plan rengini açık background-color: #FFCCCC;  /* Başlığın arka plan rengini aynı yapın *\n"
"")
        self.txeBilgiKutusu.setReadOnly(True)
        self.txeBilgiKutusu.setObjectName("txeBilgiKutusu")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1398, 26))
        self.menubar.setObjectName("menubar")
        self.menuHAKKINDA = QtWidgets.QMenu(self.menubar)
        self.menuHAKKINDA.setStyleSheet("QMenu {\n"
"    background-color: #2e2e2e; /* Menü arka plan rengi */\n"
"    color: #ffffff; /* Metin rengi */\n"
"    border: 1px solid #4d4d4d; /* Kenar rengi */\n"
"    border-radius: 8px; /* Köşeleri yuvarlama */\n"
"    padding: 8px; /* İçerik ile kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent; /* Öğelerin arka planı */\n"
"    padding: 5px 30px; /* Öğelerin iç boşluğu */\n"
"    margin: 2px 0px; /* Öğeler arasındaki boşluk */\n"
"    border-radius: 4px; /* Öğelerin köşe yuvarlama */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4d4d4d; /* Üzerine gelindiğinde arka plan rengi */\n"
"    color: #ffffff; /* Üzerine gelindiğinde metin rengi */\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px; /* Ayırıcı çizgi yüksekliği */\n"
"    background-color: #707070; /* Ayırıcı çizgi rengi */\n"
"    margin: 4px 8px; /* Ayırıcı çizgi ve kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 12px; /* Genişlik */\n"
"    height: 12px; /* Yükseklik */\n"
"}\n"
"\n"
"QMenu::\n"
"")
        self.menuHAKKINDA.setObjectName("menuHAKKINDA")
        self.menuYARDIM = QtWidgets.QMenu(self.menubar)
        self.menuYARDIM.setStyleSheet("QMenu {\n"
"    background-color: #2e2e2e; /* Menü arka plan rengi */\n"
"    color: #ffffff; /* Metin rengi */\n"
"    border: 1px solid #4d4d4d; /* Kenar rengi */\n"
"    border-radius: 8px; /* Köşeleri yuvarlama */\n"
"    padding: 8px; /* İçerik ile kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent; /* Öğelerin arka planı */\n"
"    padding: 5px 30px; /* Öğelerin iç boşluğu */\n"
"    margin: 2px 0px; /* Öğeler arasındaki boşluk */\n"
"    border-radius: 4px; /* Öğelerin köşe yuvarlama */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4d4d4d; /* Üzerine gelindiğinde arka plan rengi */\n"
"    color: #ffffff; /* Üzerine gelindiğinde metin rengi */\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px; /* Ayırıcı çizgi yüksekliği */\n"
"    background-color: #707070; /* Ayırıcı çizgi rengi */\n"
"    margin: 4px 8px; /* Ayırıcı çizgi ve kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 12px; /* Genişlik */\n"
"    height: 12px; /* Yükseklik */\n"
"}\n"
"\n"
"QMenu::\n"
"")
        self.menuYARDIM.setObjectName("menuYARDIM")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionM_SYONUMUZ_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek = QtWidgets.QAction(MainWindow)
        self.actionM_SYONUMUZ_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek.setObjectName("actionM_SYONUMUZ_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek")
        self.actionV_ZYONUMUZ_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak = QtWidgets.QAction(MainWindow)
        self.actionV_ZYONUMUZ_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak.setObjectName("actionV_ZYONUMUZ_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak")
        self.actionHer_Hakk_Sakl_d_r_2024 = QtWidgets.QAction(MainWindow)
        self.actionHer_Hakk_Sakl_d_r_2024.setObjectName("actionHer_Hakk_Sakl_d_r_2024")
        self.action_leti_im = QtWidgets.QAction(MainWindow)
        self.action_leti_im.setObjectName("action_leti_im")
        self.actionE_POSTA_dilarabebek4_gmail_com = QtWidgets.QAction(MainWindow)
        self.actionE_POSTA_dilarabebek4_gmail_com.setObjectName("actionE_POSTA_dilarabebek4_gmail_com")
        self.actionE_POSTA_dilarabebek4_gmail_com_2 = QtWidgets.QAction(MainWindow)
        self.actionE_POSTA_dilarabebek4_gmail_com_2.setObjectName("actionE_POSTA_dilarabebek4_gmail_com_2")
        self.menuHAKKINDA.addAction(self.actionM_SYONUMUZ_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek)
        self.menuHAKKINDA.addSeparator()
        self.menuHAKKINDA.addAction(self.actionV_ZYONUMUZ_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak)
        self.menuHAKKINDA.addSeparator()
        self.menuHAKKINDA.addAction(self.actionHer_Hakk_Sakl_d_r_2024)
        self.menuYARDIM.addAction(self.action_leti_im)
        self.menuYARDIM.addSeparator()
        self.menuYARDIM.addAction(self.actionE_POSTA_dilarabebek4_gmail_com_2)
        self.menubar.addAction(self.menuHAKKINDA.menuAction())
        self.menubar.addAction(self.menuYARDIM.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cmbCinsiyet.setCurrentIndex(-1)
        self.cmbKanGrubu.setCurrentIndex(-1)
        self.cmbRhFaktoru.setCurrentIndex(-1)
        self.cmbBagisTuru.setCurrentIndex(-1)
        self.cmbSehir.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblAcilIletisimBilgi.setText(_translate("MainWindow", "ACİL İLETİŞİM BİLGİLERİ"))
        self.lblYakinAdi.setText(_translate("MainWindow", "Yakınınızın Adı:"))
        self.lblYakinSoyadi.setText(_translate("MainWindow", "Yakınınızın Soyadı:"))
        self.lblYakinTelefon.setText(_translate("MainWindow", "Yakınınızın Telefon Numarası:"))
        self.lneYakinTelefon.setInputMask(_translate("MainWindow", "(999) 999-9999;_"))
        self.lblBagisciBilgi.setText(_translate("MainWindow", "BAĞIŞÇI BİLGİLERİ"))
        self.lblBagisciAdi.setText(_translate("MainWindow", "Bağışçı Adı:"))
        self.lblBagisciSoyadi.setText(_translate("MainWindow", "Bağışçı Soyadı:"))
        self.lblTc.setText(_translate("MainWindow", "TC Kimlik Numarası:"))
        self.lneTc.setInputMask(_translate("MainWindow", "99999999999;_"))
        self.lblCinsiyet.setText(_translate("MainWindow", "Cinsiyet:"))
        self.cmbCinsiyet.setItemText(0, _translate("MainWindow", "KADIN"))
        self.cmbCinsiyet.setItemText(1, _translate("MainWindow", "ERKEK"))
        self.lblDogumTarihi.setText(_translate("MainWindow", "Doğum Tarihi:"))
        self.lblIletisimBilgi.setText(_translate("MainWindow", "BAĞIŞÇI İLETİŞİM BİLGİLERİ"))
        self.lblBagisciTelefon.setText(_translate("MainWindow", "Bağışçının Telefon Numarası:"))
        self.lneBagisciTelefon.setInputMask(_translate("MainWindow", "(999) 999-9999;_"))
        self.lneBagisciTelefon.setText(_translate("MainWindow", "() -"))
        self.lblBagisciEposta.setText(_translate("MainWindow", "Bağışçının E-posta Adresi:"))
        self.lneBagisciEposta.setPlaceholderText(_translate("MainWindow", "örn:isim@ornek.com"))
        self.lblBagisciEv.setText(_translate("MainWindow", "Bağışçının Ev Adresi:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "KULLANICI BİLGİLERİ"))
        self.lblOnemliBilgi.setText(_translate("MainWindow", "ÖNEMLİ BİLGİLER"))
        self.lblNotBilgisi.setText(_translate("MainWindow", " Notunuz(ekstra bilgiler için)"))
        self.lblTibbiBilgiler.setText(_translate("MainWindow", "TIBBİ BİLGİLER"))
        self.lblKilo.setText(_translate("MainWindow", "Kilo(Kg):"))
        self.lblBoy.setText(_translate("MainWindow", "Boy(cm):"))
        self.lneBoy.setInputMask(_translate("MainWindow", "999;_"))
        self.lblKronikHastalik.setText(_translate("MainWindow", "Kronik Hastalığım var."))
        self.chkbKronikHastalik.setText(_translate("MainWindow", "Evet"))
        self.lblIlac.setText(_translate("MainWindow", "Düzenli Kullandığım bir ilaç var."))
        self.chkbIlac.setText(_translate("MainWindow", "Evet"))
        self.lblAlerji.setText(_translate("MainWindow", "Alerjim var."))
        self.chkbAlerji.setText(_translate("MainWindow", "Evet"))
        self.lblSigara.setText(_translate("MainWindow", "Sigara veya Alkol Kullanıyorum."))
        self.chkbSigara.setText(_translate("MainWindow", "Evet"))
        self.lblGecmisMudahale.setText(_translate("MainWindow", "Geçmişteki Cerrahi Müdahaleler:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "TIBBİ BİLGİLER"))
        self.lblBagisBilgi.setText(_translate("MainWindow", "BAĞIŞ BİLGİLERİ"))
        self.lblKanGrubu.setText(_translate("MainWindow", "Kan Grubu:"))
        self.cmbKanGrubu.setItemText(0, _translate("MainWindow", "A Kan Grubu"))
        self.cmbKanGrubu.setItemText(1, _translate("MainWindow", "B Kan Grubu"))
        self.cmbKanGrubu.setItemText(2, _translate("MainWindow", "AB Kan Grubu"))
        self.cmbKanGrubu.setItemText(3, _translate("MainWindow", "0 Kan Grubu"))
        self.lblRhFaktoru.setText(_translate("MainWindow", "Rh Faktörü:"))
        self.cmbRhFaktoru.setItemText(0, _translate("MainWindow", "Rh+"))
        self.cmbRhFaktoru.setItemText(1, _translate("MainWindow", "Rh-"))
        self.lblBagisTuru.setText(_translate("MainWindow", "Bağış Türü:"))
        self.cmbBagisTuru.setItemText(0, _translate("MainWindow", "Kan Bağışı"))
        self.cmbBagisTuru.setItemText(1, _translate("MainWindow", "Aferez Bağışı"))
        self.cmbBagisTuru.setItemText(2, _translate("MainWindow", "İmmun Plazma Bağışı"))
        self.cmbBagisTuru.setItemText(3, _translate("MainWindow", "Kök Hücre Bağışı"))
        self.lblSehir.setText(_translate("MainWindow", "Bağış Yapacağınız Şehir:"))
        self.cmbSehir.setItemText(0, _translate("MainWindow", "Adana"))
        self.cmbSehir.setItemText(1, _translate("MainWindow", "Adıyaman"))
        self.cmbSehir.setItemText(2, _translate("MainWindow", "Afyonkarahisar"))
        self.cmbSehir.setItemText(3, _translate("MainWindow", "Ağrı"))
        self.cmbSehir.setItemText(4, _translate("MainWindow", "Aksaray"))
        self.cmbSehir.setItemText(5, _translate("MainWindow", "Amasya"))
        self.cmbSehir.setItemText(6, _translate("MainWindow", "Ankara"))
        self.cmbSehir.setItemText(7, _translate("MainWindow", "Antalya"))
        self.cmbSehir.setItemText(8, _translate("MainWindow", "Ardahan"))
        self.cmbSehir.setItemText(9, _translate("MainWindow", "Artvin"))
        self.cmbSehir.setItemText(10, _translate("MainWindow", "Aydın"))
        self.cmbSehir.setItemText(11, _translate("MainWindow", "Balıkesir"))
        self.cmbSehir.setItemText(12, _translate("MainWindow", "Bartın"))
        self.cmbSehir.setItemText(13, _translate("MainWindow", "Batman "))
        self.cmbSehir.setItemText(14, _translate("MainWindow", "Bayburt"))
        self.cmbSehir.setItemText(15, _translate("MainWindow", "Bilecik"))
        self.cmbSehir.setItemText(16, _translate("MainWindow", "Bingöl"))
        self.cmbSehir.setItemText(17, _translate("MainWindow", "Bitlis"))
        self.cmbSehir.setItemText(18, _translate("MainWindow", "Bolu"))
        self.cmbSehir.setItemText(19, _translate("MainWindow", "Burdur"))
        self.cmbSehir.setItemText(20, _translate("MainWindow", "Bursa"))
        self.cmbSehir.setItemText(21, _translate("MainWindow", "Çanakkale"))
        self.cmbSehir.setItemText(22, _translate("MainWindow", "Çankırı"))
        self.cmbSehir.setItemText(23, _translate("MainWindow", "Çorum"))
        self.cmbSehir.setItemText(24, _translate("MainWindow", "Denizli"))
        self.cmbSehir.setItemText(25, _translate("MainWindow", "Diyarbakır"))
        self.cmbSehir.setItemText(26, _translate("MainWindow", "Düzce"))
        self.cmbSehir.setItemText(27, _translate("MainWindow", "Edirne"))
        self.cmbSehir.setItemText(28, _translate("MainWindow", "Elazığ"))
        self.cmbSehir.setItemText(29, _translate("MainWindow", "Erzincan"))
        self.cmbSehir.setItemText(30, _translate("MainWindow", "Erzurum"))
        self.cmbSehir.setItemText(31, _translate("MainWindow", "Eskişehir"))
        self.cmbSehir.setItemText(32, _translate("MainWindow", "Gaziantep"))
        self.cmbSehir.setItemText(33, _translate("MainWindow", "Giresun"))
        self.cmbSehir.setItemText(34, _translate("MainWindow", "Gümüşhane"))
        self.cmbSehir.setItemText(35, _translate("MainWindow", "Hakkari"))
        self.cmbSehir.setItemText(36, _translate("MainWindow", "Hatay"))
        self.cmbSehir.setItemText(37, _translate("MainWindow", "Iğdır"))
        self.cmbSehir.setItemText(38, _translate("MainWindow", "Isparta"))
        self.cmbSehir.setItemText(39, _translate("MainWindow", "İstanbul"))
        self.cmbSehir.setItemText(40, _translate("MainWindow", "İzmir"))
        self.cmbSehir.setItemText(41, _translate("MainWindow", "Kahramanmaraş"))
        self.cmbSehir.setItemText(42, _translate("MainWindow", "Karabük"))
        self.cmbSehir.setItemText(43, _translate("MainWindow", "Karaman"))
        self.cmbSehir.setItemText(44, _translate("MainWindow", "Kars"))
        self.cmbSehir.setItemText(45, _translate("MainWindow", "Kastamonu"))
        self.cmbSehir.setItemText(46, _translate("MainWindow", "Kayseri"))
        self.cmbSehir.setItemText(47, _translate("MainWindow", "Kırıkkale"))
        self.cmbSehir.setItemText(48, _translate("MainWindow", "Kırklareli"))
        self.cmbSehir.setItemText(49, _translate("MainWindow", "Kırşehir"))
        self.cmbSehir.setItemText(50, _translate("MainWindow", "Kilis"))
        self.cmbSehir.setItemText(51, _translate("MainWindow", "Kocaeli"))
        self.cmbSehir.setItemText(52, _translate("MainWindow", "Konya"))
        self.cmbSehir.setItemText(53, _translate("MainWindow", "Kütahya"))
        self.cmbSehir.setItemText(54, _translate("MainWindow", "Malatya"))
        self.cmbSehir.setItemText(55, _translate("MainWindow", "Manisa"))
        self.cmbSehir.setItemText(56, _translate("MainWindow", "Mardin"))
        self.cmbSehir.setItemText(57, _translate("MainWindow", "Mersin"))
        self.cmbSehir.setItemText(58, _translate("MainWindow", "Muğla"))
        self.cmbSehir.setItemText(59, _translate("MainWindow", "Muş"))
        self.cmbSehir.setItemText(60, _translate("MainWindow", "Nevşehir"))
        self.cmbSehir.setItemText(61, _translate("MainWindow", "Niğde"))
        self.cmbSehir.setItemText(62, _translate("MainWindow", "Ordu"))
        self.cmbSehir.setItemText(63, _translate("MainWindow", "Osmaniye"))
        self.cmbSehir.setItemText(64, _translate("MainWindow", "Rize"))
        self.cmbSehir.setItemText(65, _translate("MainWindow", "Sakarya"))
        self.cmbSehir.setItemText(66, _translate("MainWindow", "Samsun"))
        self.cmbSehir.setItemText(67, _translate("MainWindow", "Siirt"))
        self.cmbSehir.setItemText(68, _translate("MainWindow", "Sinop"))
        self.cmbSehir.setItemText(69, _translate("MainWindow", "Sivas"))
        self.cmbSehir.setItemText(70, _translate("MainWindow", "Şanlıurfa"))
        self.cmbSehir.setItemText(71, _translate("MainWindow", "Şırnak"))
        self.cmbSehir.setItemText(72, _translate("MainWindow", "Tekirdağ"))
        self.cmbSehir.setItemText(73, _translate("MainWindow", "Tokat"))
        self.cmbSehir.setItemText(74, _translate("MainWindow", "Trabzon"))
        self.cmbSehir.setItemText(75, _translate("MainWindow", "Tunceli"))
        self.cmbSehir.setItemText(76, _translate("MainWindow", "Uşak"))
        self.cmbSehir.setItemText(77, _translate("MainWindow", "Van"))
        self.cmbSehir.setItemText(78, _translate("MainWindow", "Yalova"))
        self.cmbSehir.setItemText(79, _translate("MainWindow", "Yozgat"))
        self.cmbSehir.setItemText(80, _translate("MainWindow", "Zonguldak"))
        self.lblIlkKanBagisi.setText(_translate("MainWindow", "İlk Defa  Kan Bağışı Yapıyorum"))
        self.label.setText(_translate("MainWindow", "(Gün/Ay/Yıl)"))
        self.lneSonKanBagisiTarihi.setInputMask(_translate("MainWindow", "99/99/9999"))
        self.lneSonKanBagisiTarihi.setText(_translate("MainWindow", "00/00/0000"))
        self.lblSonKanBagisiTarihi.setText(_translate("MainWindow", "En Son Ki Kan Bağış Tarihi:"))
        self.label_2.setText(_translate("MainWindow", "(Daha önce yapıldıysa)"))
        self.chkblkKanBagisi.setText(_translate("MainWindow", "Evet"))
        self.psbRandevuAl.setText(_translate("MainWindow", "Randevu Al"))
        self.psRandevuAra.setText(_translate("MainWindow", "Randevu Ara"))
        self.psGuncelle.setText(_translate("MainWindow", "Güncelle"))
        self.psRandevuListele.setText(_translate("MainWindow", "Randevu Listele"))
        self.psCikis.setText(_translate("MainWindow", "Çıkış"))
        self.lblKanRandevuTarihi.setText(_translate("MainWindow", " KAN BAĞIŞI İÇİN RANDEVU TARİHİ SEÇİNİZ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "BAĞIŞ YAP"))
        self.psRavdevuSil.setText(_translate("MainWindow", "Randevu Sil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "KAYIT BİLGİLERİ"))
        self.lblNedenKanBagisi.setText(_translate("MainWindow", "NEDEN KAN BAĞIŞLAMALIYIM ?"))
        self.txeNedenKanBagisi.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:400; color:#ff0000;\">Bağışlanan 1 Ünite kan bağışı ile 3 farklı ihtiyaç sahibinin tedavisine katkıda bulunmuş olursunuz.</span></p></body></html>"))
        self.lblAferez.setText(_translate("MainWindow", "AFEREZ BAĞIŞI NE İŞE YARAR?"))
        self.txeAferez.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">Anemi,lösemi,karaciğer yetmezliği,organ nakli,kemik iliği nakli,lenfoma gibi önem arz eden ve aciliyeti olan bu rahatsızlıkların tedavilerinde kullanılır.</span></p></body></html>"))
        self.lblImmun.setText(_translate("MainWindow", "İMMUN PLAZMA BAĞIŞI NEDİR?"))
        self.txeImmun.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">Covid-19 tanısı konulup,tedavi sürecinin ardından iyileşen kişilerden,kritik durumlarda olan hastalarda kullanılması için alınan kan bileşenidir.</span></p></body></html>"))
        self.lblKokHucre.setText(_translate("MainWindow", "KÖK HÜCRE NAKLİ NEDİR?"))
        self.txeKokHucre.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">Uygun donör bulunmasıyla kök hücrenin hasta kişiye(Lösemi Hastasına) nakil edilmesidir.</span></p></body></html>"))
        self.lblAferez_2.setText(_translate("MainWindow", "HANGİ ARALIKLARLA KAN BAĞIŞINDA BULUNABİLİRİM?"))
        self.txeAferez_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">Tam kan bağışında;Erkekler 90 günde bir , Kadınlar 120 gün de bir kan bağışında bulunabilirler.Aferez ve tam kan bağışı aralıkları hakkında detaylı bilgi için Ulusal Kan ve Kan Bileşenleri Hazırlama, Kullanım ve Kalite Güvencesi Rehberi 2016 (bkz. 73-74)</span></p></body></html>"))
        self.lblKokHucre_2.setText(_translate("MainWindow", "KİMLER KAN BAĞIŞINDA BULUNABİLİR?"))
        self.txeKokHucre_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">18-65 yaş aralığında 50 kilogramın üzerindeki her sağlıklı birey kan bağışçısı adayı olabilir. (19 yaşından gün almak, 65’ini doldurmamak gerekir.)</span></p></body></html>"))
        self.txeBilgiKutusu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#aa0000;\">BİLGİ KUTUSU</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "BİLGİ KUTUSU"))
        self.menuHAKKINDA.setTitle(_translate("MainWindow", "HAKKINDA"))
        self.menuYARDIM.setTitle(_translate("MainWindow", "YARDIM"))
        self.actionM_SYONUMUZ_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek.setText(_translate("MainWindow", "MİSYONUMUZ;\n"
"Hayat kurtarmak için kan bağışını teşvik ederek, toplum sağlığını iyileştirmek ve ihtiyacı olan hastalara güvenli kan temin etmek."))
        self.actionV_ZYONUMUZ_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak.setText(_translate("MainWindow", "VİZYONUMUZ;\n"
"Kan bağışının yaygınlaştığı, herkesin bağışçı olduğu ve hiçbir hastanın kan ihtiyacı yaşamayacağı bir dünya yaratmak."))
        self.actionHer_Hakk_Sakl_d_r_2024.setText(_translate("MainWindow", "Her Hakkı Saklıdır © 2024 "))
        self.action_leti_im.setText(_translate("MainWindow", "İletişim;"))
        self.actionE_POSTA_dilarabebek4_gmail_com.setText(_translate("MainWindow", "E-POSTA: dilarabebek4@gmail.com"))
        self.actionE_POSTA_dilarabebek4_gmail_com_2.setText(_translate("MainWindow", "E-POSTA: dilarabebek4@gmail.com"))
