# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 629)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 70, 381, 401))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid black;  /* Siyah renkte 2 piksel kalınlığında kenar */\n"
"    border-radius: 10px;  /* Kenarları oval yapmak için */\n"
"    margin-top: 20px;  /* Başlıkla kutu arasında boşluk */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;  /* Başlığın kenarlarla olan hizasını ayarlamak için */\n"
"    subcontrol-position: top center;  /* Başlığı yukarıda ve ortada konumlandırmak için */\n"
"    padding: 0 5px;  /* Başlığın etrafında boşluk\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lneGirisKullaniciAdi = QtWidgets.QLineEdit(self.groupBox)
        self.lneGirisKullaniciAdi.setGeometry(QtCore.QRect(10, 60, 331, 41))
        self.lneGirisKullaniciAdi.setStyleSheet("background-color: #ffccd5;\n"
"")
        self.lneGirisKullaniciAdi.setInputMask("")
        self.lneGirisKullaniciAdi.setObjectName("lneGirisKullaniciAdi")
        self.lblGirisKullanciAdi = QtWidgets.QLabel(self.groupBox)
        self.lblGirisKullanciAdi.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblGirisKullanciAdi.setFont(font)
        self.lblGirisKullanciAdi.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.lblGirisKullanciAdi.setObjectName("lblGirisKullanciAdi")
        self.psbGirisGiris = QtWidgets.QPushButton(self.groupBox)
        self.psbGirisGiris.setGeometry(QtCore.QRect(100, 220, 141, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.psbGirisGiris.setFont(font)
        self.psbGirisGiris.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #CCCCCC, stop:1 #333333); /* Tıklanınca arka plan geçişi gri tonlarında oluyor */\n"
"    border: 2px solid #333333; /* Tıklanınca kenarlık koyu gri oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"\n"
"\n"
"")
        self.psbGirisGiris.setObjectName("psbGirisGiris")
        self.lblGirisVeya = QtWidgets.QLabel(self.groupBox)
        self.lblGirisVeya.setGeometry(QtCore.QRect(150, 266, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblGirisVeya.setFont(font)
        self.lblGirisVeya.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.lblGirisVeya.setObjectName("lblGirisVeya")
        self.psbKayit = QtWidgets.QPushButton(self.groupBox)
        self.psbKayit.setGeometry(QtCore.QRect(100, 310, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.psbKayit.setFont(font)
        self.psbKayit.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #CCCCCC, stop:1 #333333); /* Tıklanınca arka plan geçişi gri tonlarında oluyor */\n"
"    border: 2px solid #333333; /* Tıklanınca kenarlık koyu gri oluyor */\n"
"    transform: scale(0.95); /* Tıklanınca buton biraz küçülüyor */\n"
"}\n"
"")
        self.psbKayit.setObjectName("psbKayit")
        self.lneGirisSifre = QtWidgets.QLineEdit(self.groupBox)
        self.lneGirisSifre.setGeometry(QtCore.QRect(10, 150, 331, 41))
        self.lneGirisSifre.setStyleSheet("background-color: #ffccd5;\n"
"")
        self.lneGirisSifre.setObjectName("lneGirisSifre")
        self.lblGirisSifre = QtWidgets.QLabel(self.groupBox)
        self.lblGirisSifre.setGeometry(QtCore.QRect(10, 130, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblGirisSifre.setFont(font)
        self.lblGirisSifre.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.lblGirisSifre.setObjectName("lblGirisSifre")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-1180, -350, 1701, 1341))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Resimler/Ekran Görüntüleri/alyuvar5.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.groupBox.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 26))
        self.menubar.setObjectName("menubar")
        self.menuHAKKINDA = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuHAKKINDA.setFont(font)
        self.menuHAKKINDA.setStyleSheet("QMenu {\n"
"    background-color: #2e2e2e; /* Menü arka plan rengi */\n"
"    color: #ffffff; /* Metin rengi */\n"
"    border: 1px solid #4d4d4d; /* Kenar rengi */\n"
"    border-radius: 8px; /* Köşeleri yuvarlama */\n"
"    padding: 8px; /* İçerik ile kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent; /* Öğelerin arka planı */\n"
"    padding: 5px 30px; /* Öğelerin iç boşluğu */\n"
"    margin: 2px 0px; /* Öğeler arasındaki boşluk */\n"
"    border-radius: 4px; /* Öğelerin köşe yuvarlama */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4d4d4d; /* Üzerine gelindiğinde arka plan rengi */\n"
"    color: #ffffff; /* Üzerine gelindiğinde metin rengi */\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px; /* Ayırıcı çizgi yüksekliği */\n"
"    background-color: #707070; /* Ayırıcı çizgi rengi */\n"
"    margin: 4px 8px; /* Ayırıcı çizgi ve kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 1px; /* Genişlik */\n"
"    height: 12px; /* Yükseklik */\n"
"}\n"
"\n"
"QMenu::\n"
"")
        self.menuHAKKINDA.setObjectName("menuHAKKINDA")
        self.menuYARDIM = QtWidgets.QMenu(self.menubar)
        self.menuYARDIM.setStyleSheet("QMenu {\n"
"    background-color: #2e2e2e; /* Menü arka plan rengi */\n"
"    color: #ffffff; /* Metin rengi */\n"
"    border: 1px solid #4d4d4d; /* Kenar rengi */\n"
"    border-radius: 8px; /* Köşeleri yuvarlama */\n"
"    padding: 8px; /* İçerik ile kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent; /* Öğelerin arka planı */\n"
"    padding: 5px 30px; /* Öğelerin iç boşluğu */\n"
"    margin: 2px 0px; /* Öğeler arasındaki boşluk */\n"
"    border-radius: 4px; /* Öğelerin köşe yuvarlama */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4d4d4d; /* Üzerine gelindiğinde arka plan rengi */\n"
"    color: #ffffff; /* Üzerine gelindiğinde metin rengi */\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px; /* Ayırıcı çizgi yüksekliği */\n"
"    background-color: #707070; /* Ayırıcı çizgi rengi */\n"
"    margin: 4px 8px; /* Ayırıcı çizgi ve kenar arasındaki boşluk */\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 1px; /* Genişlik */\n"
"    height: 12px; /* Yükseklik */\n"
"}\n"
"\n"
"QMenu::\n"
"")
        self.menuYARDIM.setObjectName("menuYARDIM")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2024 = QtWidgets.QAction(MainWindow)
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2024.setObjectName("actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2024")
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2025 = QtWidgets.QAction(MainWindow)
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2025.setObjectName("actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2025")
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2026 = QtWidgets.QAction(MainWindow)
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2026.setObjectName("actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2026")
        self.actionKan_Bankas_Uygulamas = QtWidgets.QAction(MainWindow)
        self.actionKan_Bankas_Uygulamas.setObjectName("actionKan_Bankas_Uygulamas")
        self.actionkan_ba_yapmak_isteyen = QtWidgets.QAction(MainWindow)
        self.actionkan_ba_yapmak_isteyen.setObjectName("actionkan_ba_yapmak_isteyen")
        self.action_g_n_ll_ler_ile_kan_ihtiyac = QtWidgets.QAction(MainWindow)
        self.action_g_n_ll_ler_ile_kan_ihtiyac.setObjectName("action_g_n_ll_ler_ile_kan_ihtiyac")
        self.actionolan_kurum_ve_ki_ileri_bir = QtWidgets.QAction(MainWindow)
        self.actionolan_kurum_ve_ki_ileri_bir.setObjectName("actionolan_kurum_ve_ki_ileri_bir")
        self.actionaraya_getirmek_amac_yla = QtWidgets.QAction(MainWindow)
        self.actionaraya_getirmek_amac_yla.setObjectName("actionaraya_getirmek_amac_yla")
        self.actiongeli_tirilmi_tir_Bu_uygulama = QtWidgets.QAction(MainWindow)
        self.actiongeli_tirilmi_tir_Bu_uygulama.setObjectName("actiongeli_tirilmi_tir_Bu_uygulama")
        self.actiong_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir = QtWidgets.QAction(MainWindow)
        self.actiong_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir.setObjectName("actiong_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir")
        self.actionaraya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama = QtWidgets.QAction(MainWindow)
        self.actionaraya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama.setObjectName("actionaraya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama")
        self.actionkan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda = QtWidgets.QAction(MainWindow)
        self.actionkan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda.setObjectName("actionkan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda")
        self.action_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r = QtWidgets.QAction(MainWindow)
        self.action_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r.setObjectName("action_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r")
        self.actionHer_Hakk_Sakl_d_r_2025 = QtWidgets.QAction(MainWindow)
        self.actionHer_Hakk_Sakl_d_r_2025.setObjectName("actionHer_Hakk_Sakl_d_r_2025")
        self.actionMisyonumuz_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek = QtWidgets.QAction(MainWindow)
        self.actionMisyonumuz_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek.setObjectName("actionMisyonumuz_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek")
        self.actionVizyonumuz_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak = QtWidgets.QAction(MainWindow)
        self.actionVizyonumuz_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak.setObjectName("actionVizyonumuz_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak")
        self.actionHer_Hakk_Sakl_d_r_2026 = QtWidgets.QAction(MainWindow)
        self.actionHer_Hakk_Sakl_d_r_2026.setObjectName("actionHer_Hakk_Sakl_d_r_2026")
        self.action_leti_im = QtWidgets.QAction(MainWindow)
        self.action_leti_im.setObjectName("action_leti_im")
        self.actionE_POSTA_dilarabebek4_gmail_com = QtWidgets.QAction(MainWindow)
        self.actionE_POSTA_dilarabebek4_gmail_com.setObjectName("actionE_POSTA_dilarabebek4_gmail_com")
        self.menuHAKKINDA.addAction(self.actionMisyonumuz_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek)
        self.menuHAKKINDA.addSeparator()
        self.menuHAKKINDA.addAction(self.actionVizyonumuz_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak)
        self.menuHAKKINDA.addSeparator()
        self.menuHAKKINDA.addAction(self.actionHer_Hakk_Sakl_d_r_2026)
        self.menuYARDIM.addAction(self.action_leti_im)
        self.menuYARDIM.addSeparator()
        self.menuYARDIM.addAction(self.actionE_POSTA_dilarabebek4_gmail_com)
        self.menubar.addAction(self.menuHAKKINDA.menuAction())
        self.menubar.addAction(self.menuYARDIM.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblGirisKullanciAdi.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.psbGirisGiris.setText(_translate("MainWindow", "GİRİŞ YAP"))
        self.lblGirisVeya.setText(_translate("MainWindow", "veya"))
        self.psbKayit.setText(_translate("MainWindow", "KAYIT OL"))
        self.lblGirisSifre.setText(_translate("MainWindow", "Şifre"))
        self.label_2.setText(_translate("MainWindow", "KULLANICI GİRİŞ"))
        self.menuHAKKINDA.setTitle(_translate("MainWindow", "HAKKINDA"))
        self.menuYARDIM.setTitle(_translate("MainWindow", "YARDIM"))
        self.action_6.setText(_translate("MainWindow", "2024"))
        self.action_7.setText(_translate("MainWindow", "andkdks"))
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2024.setText(_translate("MainWindow", "Kan Bankası Uygulaması\n"
"\n"
"Kan Bankası Uygulaması, kan bağışı yapmak isteyen gönüllüler ile kan ihtiyacı olan kurum ve kişileri bir araya getirmek amacıyla geliştirilmiştir. Bu uygulama, kan bağışı yapma sürecini kolaylaştırmak ve toplumda kan bağışı bilincini artırmak için tasarlanmıştır.\n"
"\n"
"Her Hakkı Saklıdır © 2024"))
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2025.setText(_translate("MainWindow", "Kan Bankası Uygulaması\n"
"\n"
"Kan Bankası Uygulaması, kan bağışı yapmak isteyen gönüllüler ile kan ihtiyacı olan kurum ve kişileri bir araya getirmek amacıyla geliştirilmiştir. Bu uygulama, kan bağışı yapma sürecini kolaylaştırmak ve toplumda kan bağışı bilincini artırmak için tasarlanmıştır.\n"
"\n"
"Her Hakkı Saklıdır © 2024"))
        self.actionKan_Bankas_Uygulamas_Kan_Bankas_Uygulamas_kan_ba_yapmak_isteyen_g_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir_araya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama_kan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r_Her_Hakk_Sakl_d_r_2026.setText(_translate("MainWindow", "Kan Bankası Uygulaması \n"
"\n"
"Kan Bankası Uygulaması,  \n"
"\n"
"kan bağışı yapmak isteyen \n"
"\n"
" gönüllüler ile kan ihtiyacı  \n"
"\n"
"olan kurum ve kişileri bir  \n"
"\n"
"araya getirmek amacıyla \n"
"\n"
" geliştirilmiştir. Bu uygulama, \n"
"\n"
" kan bağışı yapma sürecini  \n"
"\n"
"kolaylaştırmak ve toplumda \n"
"\n"
" kan bağışı bilincini artırmak \n"
"\n"
" için tasarlanmıştır. \n"
"\n"
"Her Hakkı Saklıdır © 2024 "))
        self.actionKan_Bankas_Uygulamas.setText(_translate("MainWindow", "Kan Bankası Uygulaması kan bağışı yapmak isteyen  "))
        self.actionkan_ba_yapmak_isteyen.setText(_translate("MainWindow", "kan bağışı yapmak isteyen "))
        self.action_g_n_ll_ler_ile_kan_ihtiyac.setText(_translate("MainWindow", " gönüllüler ile kan ihtiyacı  "))
        self.actionolan_kurum_ve_ki_ileri_bir.setText(_translate("MainWindow", "olan kurum ve kişileri bir  "))
        self.actionaraya_getirmek_amac_yla.setText(_translate("MainWindow", "araya getirmek amacıyla"))
        self.actiongeli_tirilmi_tir_Bu_uygulama.setText(_translate("MainWindow", "geliştirilmiştir. Bu uygulama,"))
        self.actiong_n_ll_ler_ile_kan_ihtiyac_olan_kurum_ve_ki_ileri_bir.setText(_translate("MainWindow", "gönüllüler ile kan ihtiyacı\n"
"olan kurum ve kişileri bir"))
        self.actionaraya_getirmek_amac_yla_geli_tirilmi_tir_Bu_uygulama.setText(_translate("MainWindow", "araya getirmek amacıyla geliştirilmiştir. Bu uygulama, "))
        self.actionkan_ba_yapma_s_recini_kolayla_t_rmak_ve_toplumda.setText(_translate("MainWindow", "kan bağışı yapma sürecini kolaylaştırmak ve toplumda "))
        self.action_kan_ba_bilincini_art_rmak_i_in_tasarlanm_t_r.setText(_translate("MainWindow", " kan bağışı bilincini artırmak için tasarlanmıştır."))
        self.actionHer_Hakk_Sakl_d_r_2025.setText(_translate("MainWindow", "Her Hakkı Saklıdır © 2024 "))
        self.actionMisyonumuz_Hayat_kurtarmak_i_in_kan_ba_n_te_vik_ederek_toplum_sa_l_n_iyile_tirmek_ve_ihtiyac_olan_hastalara_g_venli_kan_temin_etmek.setText(_translate("MainWindow", "MİSYONUMUZ;\n"
"Hayat kurtarmak için kan bağışını teşvik ederek, toplum sağlığını iyileştirmek ve ihtiyacı olan hastalara güvenli kan temin etmek."))
        self.actionVizyonumuz_Kan_ba_n_n_yayg_nla_t_herkesin_ba_oldu_u_ve_hi_bir_hastan_n_kan_ihtiyac_ya_amayaca_bir_d_nya_yaratmak.setText(_translate("MainWindow", "VİZYONUMUZ;\n"
"Kan bağışının yaygınlaştığı, herkesin bağışçı olduğu ve hiçbir hastanın kan ihtiyacı yaşamayacağı bir dünya yaratmak."))
        self.actionHer_Hakk_Sakl_d_r_2026.setText(_translate("MainWindow", "Her Hakkı Saklıdır © 2024 "))
        self.action_leti_im.setText(_translate("MainWindow", "İletişim;"))
        self.actionE_POSTA_dilarabebek4_gmail_com.setText(_translate("MainWindow", "E-POSTA: dilarabebek4@gmail.com"))
